### PR TITLE
Fix #186 - Add Nexus finalizers to ClusterRole

### LINKED ISSUE #186: [blocker] Nexus Deployment stuck on OpenShift 4.x
**Describe the bug**
When trying to create a simple Nexus3 instance with the example "CentOS No Persistence", I got:

```
2020-11-01T14:29:25.381Z	INFO	controllers.Nexus	Reconciling Nexus
2020-11-01T14:29:25.389Z	DEBUG	Fetching the latest micro from minor 28
2020-11-01T14:29:25.389Z	DEBUG	Replacing 'spec.image' (docker.io/sonatype/nexus3:3.28.1) with 'docker.io/sonatype/nexus3:3.28.1'
2020-11-01T14:29:25.396Z	INFO	Generating required resources
2020-11-01T14:29:25.396Z	DEBUG	Generating required Deployment
2020-11-01T14:29:25.396Z	DEBUG	Generating required Service
2020-11-01T14:29:25.396Z	DEBUG	Generating required Service Account
2020-11-01T14:29:25.396Z	DEBUG	Generating required Secret
2020-11-01T14:29:25.396Z	INFO	Fetching deployed resources
2020-11-01T14:29:25.396Z	INFO	Attempting to fetch	{"deployed": "Deployment"}
2020-11-01T14:29:25.396Z	DEBUG	There is no deployed Deployment
2020-11-01T14:29:25.396Z	INFO	Attempting to fetch	{"deployed": "Service"}
2020-11-01T14:29:25.396Z	DEBUG	There is no deployed Service
2020-11-01T14:29:25.396Z	INFO	Attempting to fetch	{"deployed": "Persistent Volume Claim"}
2020-11-01T14:29:25.396Z	DEBUG	There is no deployed Persistent Volume Claim
2020-11-01T14:29:25.396Z	INFO	Attempting to fetch	{"deployed": "Secret"}
2020-11-01T14:29:25.396Z	DEBUG	There is no deployed Secret
2020-11-01T14:29:25.396Z	INFO	Attempting to fetch	{"deployed": "Service Account"}
2020-11-01T14:29:25.396Z	DEBUG	There is no deployed Service Account
2020-11-01T14:29:25.396Z	INFO	Attempting to fetch	{"deployed": "Route"}
2020-11-01T14:29:25.396Z	DEBUG	There is no deployed Route
2020-11-01T14:29:25.396Z	INFO	Attempting to fetch	{"deployed": "Ingress"}
2020-11-01T14:29:25.396Z	DEBUG	There is no deployed Ingress
2020-11-01T14:29:25.396Z	INFO	controllers.Nexus	Will 	{"create ": 1, ", update ": 0, ", delete ": 0, " instances of ": "v1.Deployment"}
2020-11-01T14:29:25.410Z	INFO	controllers.Nexus	Updating application status before leaving
2020-11-01T14:29:25.410Z	INFO	controllers.Nexus	Checking Deployment Status
2020-11-01T14:29:25.410Z	INFO	controllers.Nexus	Controller finished reconciliation
2020-11-01T14:29:25.410Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "apps.m88i.io", "reconcilerKind": "Nexus", "controller": "nexus", "name": "nexus3", "namespace": "nexus", "error": "deployments.apps \"nexus3\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:246
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:90
```

It's stucking in the deployment creation.

**To Reproduce**
1. Deploy the operator with the `nexus-operator.yaml` file
2. Deploy the example "CentOS No Persistence"

**Expected behavior**
Deployment and other resources to be created

**Environment**
OpenShift 4.5

### PR DESCRIPTION
**Pull request by ricardozanini**
Fixes #186 

Looks like my local environment updated the controller-gen to the latest patch, so small changes were made. I tested locally and everything looks in good shape. To test this pr:

```
kubectl apply -f https://gist.githubusercontent.com/ricardozanini/33b3cea435e53f79e8a724a250da3449/raw/78ccdae1a12fe23253a78d414fab8463b977dd91/nexus-operator-v0.4.0-cr5.yaml
```

Signed-off-by: Ricardo Zanini <zanini@redhat.com>

### CODE REVIEW

**Comment by ricardozanini** [comment]
Bah, controller-gen version is been enforced by the Makefile, will fix.

File: hack/generate-toc.sh [hunk 1]
```diff
@@ -13,6 +13,10 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+declare readme_changed=$(git status -s | grep  'README.md' || :)
+if [ -z "${readme_changed}" ]; then
+  exit 0
+fi
```
Comment (LCaparelli) [inline hack/generate-toc.sh:19]: Nice!

**Review by LCaparelli — APPROVED** [review]
Thanks a lot @ricardozanini!
